### PR TITLE
Added getter for tracking state

### PR DESCRIPTION
**Pull request by laxnpander**
When using OpenVSLAM as a library for an application, accessing the tracker state is one of the most fundamental information. It decides whether or not I can perform my own algorithms or not. Due to the fact, that the "image feeding"-functions always return a matrix, even though tracking was lost, it is very laborious to check if I can use the pose or not. Checking the state of the tracking should be as easy as calling a simple getter.

### CODE REVIEW

**Comment by shinsumicco** [comment]
@laxnpander   
Thanks!
Could you rebase your pull-request branch to the latest master one?

**Comment by laxnpander** [comment]
@shinsumicco: Should be done!

**Comment by j-p-e** [comment]
seconded - can we merge ?

**Comment by laxnpander** [comment]
I know you guys are probably busy, but such a small modification shouldn't take 3 months to merge... what can we do to help progress faster?

**Comment by dwiel** [comment]
ready to merge?

**Pull request closed without merging**
