### PR TITLE
Update g2o and Pangolin installation procedure

### PR DESCRIPTION
**Pull request by vwvw**
Update g2o installation procedure to match recommended git commit.

### CODE REVIEW

**Comment by shinsumicco** [comment]
Thanks.
Is this modification based on our `Dockerfile`?

**Comment by vwvw** [comment]
No, it is the tested commit listed a bit [above](https://github.com/xdspacelab/openvslam/blob/master/docs/installation.rst#requirements-for-openvslam)

**Comment by vwvw** [comment]
I added the tested Pangolin commit too

**Comment by shinsumicco** [comment]
Merged. Thanks!!

**Pull request merged**
