### PR TITLE
Adding support for stereo live camera SLAM

### PR DESCRIPTION
**Pull request by vwvw**
The live SLAM example only handled monocular stream. I added support for stereo stream.
For my own use, I added support for image rectification in both monocular and stereo live stream. Would you be interested in it?

### CODE REVIEW

**Comment by shinsumicco** [comment]
@vwvw 
Thank you very much! I'll review the PR within a few days.

At a glance, stereo-rectification process doesn't seem to be included in the source code.
Is it not needed for your case?
If you are kindly willing to add it to the source code, I'll update the samples for EuRoC stereo sequences to help you implement it.

**Comment by vwvw** [comment]
I needed it for my usecase buit did not include it in the PR. How do you see the config file evolution?
In my case, I had different fx,fy,cx,cy for both camera.
I used [initUndistortRectifyMap](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html#ga7dfb72c9cf9780a347fbe3d1c47e5d5a) which result in additional matrices (rectification and projection matrices) for both cameras.
Do you have any example where you used such parameters already? I was contemplating doing either a single config file or one for each  camera.

**Comment by vwvw** [comment]
By the way, would it be possible to make the wercker CI output public?

**Comment by shinsumicco** [comment]
Thanks for the quick reply.
I think the stereo rectification process is needed for stereo tracking function.
I would be grateful if you could implement it on the PR.

As far as I heard from you, you've implement the rectification like [here](https://github.com/xdspacelab/openvslam/blob/master/example/run_euroc_slam.cc#L149-L161) and [here](https://github.com/xdspacelab/openvslam/blob/master/example/run_euroc_slam.cc#L196-L197), haven't you?

I think the rectification parameters [listed here](https://github.com/xdspacelab/openvslam/blob/master/example/run_euroc_slam.cc#L150-L157) should be specified via a single config yaml file.
If you agree, I'll prepare the example configuration by updating the EuRoC stereo samples.

**Comment by shinsumicco** [comment]
I've checked the documentation of wercker but couldn't find the way to make CI logs public. Sorry for inconvenience.
If you need it, I will paste it here.

**Comment by vwvw** [comment]
> As far as I heard from you, you've implement the rectification like here and here, haven't you?

Yeah exactly. I was just looking for a nice way to pass the config than hardcoding it.

> I think the rectification parameters listed here should be specified via a single config yaml file.
Yeah exactly. It's just a bit confusing to pass fx, fy, cx, cy in addition to K_l, K_r as they are already present in the K matrices IIRC

**Comment by vwvw** [comment]
Added support for #138

**Comment by shinsumicco** [comment]
Could you apply `clang-format` to `example/run_camera_slam.cc`?

```
$ clang-format-6.0 -style=file -i example/run_camera_slam.cc
```

**Pull request merged**
