### PR TITLE
WIP: Stereo fisheye

### PR DESCRIPTION
**Pull request by matsuren**
[WIP] Stereo fisheye OpenVSLAM.

### CODE REVIEW

**Comment by Dorothy-2016** [comment]
@matsuren  have you test on a real double fisheye cameras?

**Comment by matsuren** [comment]
Hi @Dorothy-2016,
Yes, I tried with the following cameras and lenses.
 
- PointGrey Grasshopper3 GS3-U3-41C6C-C
- Fujinon FE185C086HA-1

Thanks,

**Comment by Dorothy-2016** [comment]
> Hi @Dorothy-2016,
> Yes, I tried with the following cameras and lenses.
> 
>     * PointGrey Grasshopper3 GS3-U3-41C6C-C
> 
>     * Fujinon FE185C086HA-1
> 
> 
> Thanks,

That's great! 
Can you kindly upload one dataset recorderd by one of these two cameras and lenses and its config.yaml? I also want to test on a stereo-fisheye dataset but I don't have a device like that. 
and another reason is that the TumVI dataset cannot download now.
Really thanks very much!

**Comment by matsuren** [comment]
Hi @Dorothy-2016 

I'm sorry, but It's difficult to share our dataset since experiments were conducted with a company.
You use some datasets from [TUM VI}(https://vision.in.tum.de/data/datasets/visual-inertial-dataset). I just made sure that download links work property.

Thanks,

**Pull request closed without merging**
